version: '3.7'

services:
  simple:
    container_name: simple
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5000:80
    environment:
      - CHOKIDAR_USEPOLLING=true
